<template>
  <ft-flex-box
    ref="sideNav"
    class="sideNav"
    :class="[{closed: !isOpen}, applyHiddenLabels]"
  >
    <div
      class="inner"
      :class="applyHiddenLabels"
    >
      <div
        class="navOption topNavOption mobileShow"
        role="link"
        tabindex="0"
        :title="$t('Subscriptions.Subscriptions')"
        @click="navigate('subscriptions')"
        @keydown.enter.prevent="navigate('subscriptions')"
        @keydown.space.prevent="navigate('subscriptions')"
      >
        <div
          class="thumbnailContainer"
        >
          <font-awesome-icon
            icon="rss"
            class="navIcon"
            :class="applyNavIconExpand"
            fixed-width
          />
        </div>
        <p
          v-if="!hideText"
          class="navLabel"
        >
          {{ $t("Subscriptions.Subscriptions") }}
        </p>
      </div>
      <div
        v-if="!hideTrendingVideos"
        class="navOption mobileHidden"
        role="link"
        tabindex="0"
        :title="$t('Trending.Trending')"
        @click="navigate('trending')"
        @keydown.enter.prevent="navigate('trending')"
        @keydown.space.prevent="navigate('trending')"
      >
        <div
          class="thumbnailContainer"
        >
          <font-awesome-icon
            icon="fire"
            class="navIcon"
            :class="applyNavIconExpand"
            fixed-width
          />
        </div>
        <p
          v-if="!hideText"
          class="navLabel"
        >
          {{ $t("Trending.Trending") }}
        </p>
      </div>
      <div
        v-if="!hidePopularVideos"
        class="navOption mobileHidden"
        role="link"
        tabindex="0"
        :title="$t('Most Popular')"
        @click="navigate('popular')"
        @keydown.enter.prevent="navigate('popular')"
        @keydown.space.prevent="navigate('popular')"
      >
        <div
          class="thumbnailContainer"
        >
          <font-awesome-icon
            icon="users"
            class="navIcon"
            :class="applyNavIconExpand"
            fixed-width
          />
        </div>
        <p
          v-if="!hideText"
          class="navLabel"
        >
          {{ $t("Most Popular") }}
        </p>
      </div>
      <div
        v-if="!hidePlaylists"
        class="navOption mobileShow"
        role="link"
        tabindex="0"
        :title="$t('Playlists')"
        @click="navigate('userplaylists')"
        @keydown.enter.prevent="navigate('userplaylists')"
        @keydown.space.prevent="navigate('userplaylists')"
      >
        <div
          class="thumbnailContainer"
        >
          <font-awesome-icon
            icon="bookmark"
            class="navIcon"
            :class="applyNavIconExpand"
            fixed-width
          />
        </div>
        <p
          v-if="!hideText"
          class="navLabel"
        >
          {{ $t("Playlists") }}
        </p>
      </div>
      <side-nav-more-options
        @navigate="navigate"
      />
      <div
        class="navOption mobileShow"
        role="link"
        tabindex="0"
        :title="$t('History.History')"
        @click="navigate('history')"
        @keydown.enter.prevent="navigate('history')"
        @keydown.space.prevent="navigate('history')"
      >
        <div
          class="thumbnailContainer"
        >
          <font-awesome-icon
            icon="history"
            class="navIcon"
            :class="applyNavIconExpand"
            fixed-width
          />
        </div>
        <p
          v-if="!hideText"
          class="navLabel"
        >
          {{ $t("History.History") }}
        </p>
      </div>
      <hr>
      <div
        class="navOption mobileShow"
        role="link"
        tabindex="0"
        :title="$t('Settings.Settings')"
        @click="navigate('settings')"
        @keydown.enter.prevent="navigate('settings')"
        @keydown.space.prevent="navigate('settings')"
      >
        <div
          class="thumbnailContainer"
        >
          <font-awesome-icon
            icon="sliders-h"
            class="navIcon"
            :class="applyNavIconExpand"
            fixed-width
          />
        </div>
        <p
          v-if="!hideText"
          class="navLabel"
        >
          {{ $t('Settings.Settings') }}
        </p>
      </div>
      <div
        class="navOption mobileHidden"
        role="link"
        tabindex="0"
        :title="$t('About.About')"
        @click="navigate('about')"
        @keydown.enter.prevent="navigate('about')"
        @keydown.space.prevent="navigate('about')"
      >
        <div
          class="thumbnailContainer"
        >
          <font-awesome-icon
            icon="info-circle"
            class="navIcon"
            :class="applyNavIconExpand"
            fixed-width
          />
        </div>
        <p
          v-if="!hideText"
          class="navLabel"
        >
          {{ $t("About.About") }}
        </p>
      </div>
      <hr>
      <div
        v-if="!hideActiveSubscriptions"
      >
        <div
          v-for="(channel, index) in activeSubscriptions"
          :key="index"
          class="navChannel mobileHidden"
          :title="channel.name"
          role="link"
          tabindex="0"
          @click="$goToChannel(channel.id)"
          @keydown.enter.prevent="$goToChannel(channel.id)"
        >
          <div
            class="thumbnailContainer"
          >
            <img
              class="channelThumbnail"
              :src="channel.thumbnail"
              alt=""
            >
          </div>
          <p
            v-if="isOpen"
            id="navLabelChannel"
            class="navLabel"
          >
            {{ channel.name }}
          </p>
        </div>
      </div>
    </div>
  </ft-flex-box>
</template>

<script src="./side-nav.js" />
<style scoped src="./side-nav.css" />
