name: Bug Report
description: Report an issue or unexpected behavior that occurs within the application
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        **README: Before You Submit Your Issue**
        - Please check other open and closed issues for a similar bug before reporting a new one.
        - Make sure you are on the latest release of FreeTube before submitting an issue.
  - type: checkboxes
    id: guidelines
    attributes:
      label: Guidelines
      description: By submitting this issue, you agree with the checkboxes below
      options:
        - label: This issue is not a duplicate
          required: true
        - label: I'm using the latest version
          required: true
  - type: textarea
    id: behavior
    attributes: 
      label: Behavior of the program
      description: Please write a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expectedBehavior
    attributes: 
      label: Expected behavior
      description: Please describe clear and concise what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes: 
      label: Steps To Reproduce
      description: Please add all steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: videoLink
    attributes:
      label: Link to video (if applicable)
      description: |
        If you refer to a problem which occurs within a specific video, or a range of videos, please link at least one here.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if applicable)
      description: If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.
  - type: input
    id: os
    attributes:
      label: 'OS'
      placeholder: 'e.g. Windows, Mac, Ubuntu, Fedora, Arch, etc.'
    validations:
      required: true
  - type: input
    id: osVersion
    attributes:
      label: 'OS Version'
      placeholder: 'e.g. Windows 10, Ubuntu 20.04'
    validations:
      required: true
  - type: input
    id: freetubeVersion
    attributes:
      label: 'FreeTube Version'
      placeholder: 'e.g. 0.9.0, Nightly build?'
    validations:
      required: true
  - type: input
    id: installationMethod
    attributes:
      label: 'Installation Method (If applicable)'
      placeholder: 'e.g. Portable, .exe, .deb, .AppImage, FlatHub'
    validations:
      required: false
  - type: dropdown
    attributes: 
      label: Primary API used
      description: What is the primary API being used?
      multiple: false
      options:
        - api: Local API
        - api: Invidious API
    validations:
      required: false
  - type: textarea
    id: additional
    attributes: 
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
