name: Discussion
description: Open up a new discussion about anything related to the project.
labels: "Discussion"
body:
- type: checkboxes
  attributes:
    label: Guidelines
    description: Please ensure you've completed all of the following.
    options:
        - label: I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a discussion that matches the one i want to file, without success.
          required: true
- type: checkboxes
    id: topic
    attributes:
      label: Topic
      description: Please select what topic your discussion is about.
      options:
        - label: Coding
          required: false
        - label: Contribution
          required: false
        - label: Languages
          required: false
        - label: Setup
          required: false
        - label: Other
          required: false
  - type: textarea
    id: discussion
    attributes: 
      label: Discussion
      description: Please write down whatever you want to discuss.
    validations:
      required: true
