name: Feature request
description: Suggest an idea for FreeTube which you would like to see in a future release
title: "[Feature Request]: "
labels: "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        **README: Before You Submit Your Issue**
        - Issues are not a place to go ask support questions or start discussions. Please ask support questions or start discussions on the [discussions page](https://github.com/FreeTubeApp/FreeTube/discussions).
  - type: checkboxes
    attributes:
      label: Guidelines
      description: Please ensure you've completed all of the following.
      options:
          - label: I have [searched the issue tracker for open and closed issues](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+sort%3Arelevance-desc) that are similar to the feature request I want to file, without success.
            required: true
          - label: I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
            required: true
          - label: This issue contains only one feature request.
            required: true
          - label: I have read and agree to follow the [rules](https://docs.freetubeapp.io/community/rules/).
            required: true
  - type: textarea
    attributes:
      label: Problem Description
      description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 'Issue Labels'
      description: Please select a label that fits this feature request. Choose multiple, if applicable.
      multiple: true
      options:
        - display more information to user
        - ease of use improvement
        - improvement to existing feature
        - new feature
        - new keyboard shortcut
        - new optional setting
        - support for external software
        - visual improvement
    validations:
      required: true
  - type: input
    attributes:
      label: FreeTube Version
      description: |
        If using releases, enter the version.
        If using nightly builds, enter commit hash or build number, you can find it via about page in the FreeTube application.
      placeholder: v0.14.0, 8c4278
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System Version
      description: What operating system version are you using? On Windows, click Start button > Settings > System > About. On macOS, click the Apple Menu > About This Mac. On Linux, use lsb_release or uname -a.
      placeholder: "e.g. Windows 10 version 1909, macOS Catalina 10.15.7, or Ubuntu 20.04"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation Method
      description: If you are using an unofficial installation method, please verify that the requested feature is not already available in one of the official installation methods. If the feature only relates to an unofficial installation, please direct the request to the maintainer of that installation method instead.
      options:
        - .AppImage
        - .deb
        - .dmg
        - .exe
        - Flathub
        - .pacman
        - Portable
        - .rpm
        - .zip / .7z
        - .apk (FreeTubeAndroid Unofficial)
        - .apk (Alpine Linux Package Unofficial)
        - AUR (Unofficial)
        - Chocolatey (Unofficial)
        - Homebrew (Unofficial)
        - Nix (Unofficial)
        - PortableApps (Unofficial)
        - Scoop (Unofficial)
        - Snapcraft (Unofficial)
        - WAPT (Unofficial)
        - winget (Unofficial)
        - other
    validations:
      required: true
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots or videos
      description: If applicable, add screenshots or videos to help explain your request.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Add any other context about the feature request here.
