name: Question
description: Ask a question which is not a bug or a feature request
labels: "question"
body:
  - type: checkboxes
    attributes:
      label: Guidelines
      description: Please ensure you've completed all of the following.
      options:
        - label: I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a question that matches the one i want to file, without success.
          required: true
  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: Please select what topic your discussion is about.
      multiple: true
      options:
        - Coding
        - Contribution
        - Languages
        - Setup
        - Other
    validations:
      required: true
  - type: textarea
    id: question
    attributes: 
      label: Question
      description: Please write down your question.
    validations:
      required: true
