name: Question
description: Ask a question which is not a bug or a feature request
labels: "question"
body:
  - type: checkboxes
  attributes:
    label: Guidelines
    description: Please ensure you've completed all of the following.
    options:
        - label: I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a question that matches the one i want to file, without success.
          required: true
- type: checkboxes
    id: topic
    attributes:
      label: Topic
      description: Please select what topic your discussion is about.
      options:
        - label: Coding
          required: false
        - label: Contribution
          required: false
        - label: Languages
          required: false
        - label: Setup
          required: false
        - label: Other
          required: false
  - type: textarea
    id: question
    attributes: 
      label: Question
      description: Please write down your question.
    validations:
      required: true
