name: ci

on:
  pull_request:
    branches:
      - master
      - development

env:
  NODE_VERSIONS: [14.x]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ${{ env.NODE_VERSIONS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm run ci

      - name: Execute eslint checks
        run: npm run lint

  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ${{ env.NODE_VERSIONS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm run ci

      - name: Execute prettier checks
        run: npm run prettier

  unittests:
    runs-on: ubuntu-18.04
    needs: [lint, format]

    strategy:
      matrix:
        node-version: ${{ env.NODE_VERSIONS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm run ci

      - name: Execute unit tests
        run: npm run test:unit

  e2e:
    runs-on: ubuntu-latest
    needs: [lint, format, unittests]

    strategy:
      matrix:
        node-version: ${{ env.NODE_VERSIONS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm run ci

      - name: Execute e2e tests
        run: npm run test:e2e-headless
