name: Changes Requested
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize]

jobs:
  update-pr-labels:
    runs-on: ubuntu-latest
    name: Update PR Labels
    steps:
      - name: Update Labels
        uses: danilo-delbusso/pr-review-labeller@v1.1.1
        with:
          changes-requested-label-name: "PR: changes requested"
          updated-pr-label-name: "PR: waiting for review"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
