name: "Issue Labeler"
on:
  issues:
    types: [opened]

permissions: {}

jobs:
  triage:
    runs-on: ubuntu-slim

    permissions:
      contents: read
      issues: write

    steps:
    - uses: github/issue-labeler@ccca1e16fcb66762200e616fc29b57b940c1cb67 #v3.5
      with:
        configuration-path: .github/issue-labeler.yml
        enable-versioned-regex: 0
        repo-token: ${{ secrets.GITHUB_TOKEN }}
